# Experiment 8 EDA 18/02/2026
### Name : Tanmay Agarwal
### PRN : 25070123158
### Batch : EnTC A-3
### Title: Tools for EDA- Study of NumPy Library

In [ ]:
# Declaration of Numpy

import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([[1, 2, 3], [4, 5, 6]])

print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Dimension of Array

print("Dimension of array A is: ", a.ndim)
print("Dimension of array B is: ", b.ndim )

Dimension of array A is:  1
Dimension of array B is:  2


In [ ]:
# Shape of an Array

print("Shape of A: ", a.shape)
print("Shape of B: ", b.shape)

Shape of A:  (4,)
Shape of B:  (2, 3)


In [ ]:
# Data type of elements in an array

print("The data type of elements in A is", a.dtype)
print("The data type of elements in B is", b.dtype)

The data type of elements in A is int64
The data type of elements in B is int64


# In-built functions in NumPy

In [ ]:
# Printing a Zero Matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Printing an Identity Matrix

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Diagonal matrix

np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# printing a range of range with Step Size

np.arange(1,11,2) # Same as range function, stop value is not included

array([1, 3, 5, 7, 9])

In [ ]:
# dividing a number into specified terms

np.linspace(0,1,5) # 1 is also included

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
# Arithmetic oprations in Arrays

c = a * 2
d = a + 5
print(c, "\n")
print (d)

[20 40 60 80] 

[15 25 35 45]


In [ ]:
# Mean of elements in an array

print("The average of elements in A is: ",np.mean(a))
print("The average of elements in B is: ",np.mean(b))

The average of elements in A is:  25.0
The average of elements in B is:  3.5


In [ ]:
# Median of elements

print("Median of A: ", np.median(a))
print("Median of B: ", np.median(b))

''' For clean data mean and median are same, if different take the value of median which is more appropriate'''

Median of A:  25.0
Median of B:  3.5


' For clean data mean and median are same, if different take the value of median which is more appropriate'

In [29]:
# Aggregate Functions

print("Operations performed in Matrix A")
print("Max of A: ",np.max(a))
print("Min of A: ",np.min(a))
print("Sum of A: ",np.sum(a), "\n")


print("Operations Performed in Matrix B")
print("MAx of B: ", np.max(b))
print("Min of B: ", np.min(b))
print("Sum of B: ", np.sum(b))

Operations performed in Matrix A
Max of A:  40
Min of A:  10
Sum of A:  100 

Operations Performed in Matrix B
MAx of B:  6
Min of B:  1
Sum of B:  21
